"use client";

import React, { use, useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { 
  Dialog, 
  DialogContent, 
  DialogHeader, 
  DialogTitle, 
  DialogTrigger,
  DialogDescription
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { ArrowLeft, FileText, Download, Plus, Eye, Loader2, Calendar, User, ClipboardList } from "lucide-react";
import jsPDF from "jspdf";

export default function PatientRecords({ params: paramsPromise }) {
  const params = use(paramsPromise);
  const id = params.id;
  const router = useRouter();

  const [records, setRecords] = useState([]);
  const [loading, setLoading] = useState(true);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [selectedRecord, setSelectedRecord] = useState(null);

  const [newRecord, setNewRecord] = useState({
    type: "Prescription",
    doctor: "Dr. Mukit",
    diagnosis: "",
    medicines: "",
    note: ""
  });

  useEffect(() => {
    async function fetchRecords() {
      try {
        const res = await fetch(`/api/patients/${id}/records`);
        const data = await res.json();
        setRecords(data || []);
      } catch (err) {
        console.error("Fetch error:", err);
      } finally {
        setLoading(false);
      }
    }
    fetchRecords();
  }, [id]);

  const handleAddRecord = async (e) => {
    e.preventDefault();
    setIsSubmitting(true);
    try {
      const res = await fetch(`/api/patients/${id}/records`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(newRecord),
      });
      if (res.ok) {
        const savedRecord = await res.json();
        setRecords([savedRecord, ...records]);
        setNewRecord({ type: "Prescription", doctor: "Dr. Mukit", diagnosis: "", medicines: "", note: "" });
      }
    } catch (err) {
      console.error(err);
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleDownloadPDF = (record) => {
    const doc = new jsPDF();
    doc.setFillColor(37, 99, 235);
    doc.rect(0, 0, 210, 40, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.text("MEDICAL PRESCRIPTION", 105, 25, { align: "center" });
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(`Doctor: ${record.doctor}`, 20, 55);
    doc.text(`Date: ${new Date(record.createdAt || Date.now()).toLocaleDateString()}`, 150, 55);
    doc.setFont("helvetica", "normal");
    doc.text(`Patient ID: ${id}`, 20, 65);
    doc.line(20, 70, 190, 70);
    doc.setFont("helvetica", "bold");
    doc.text("DIAGNOSIS:", 20, 85);
    doc.setFont("helvetica", "normal");
    const diagnosisLines = doc.splitTextToSize(record.diagnosis || "N/A", 170);
    doc.text(diagnosisLines, 20, 92);
    doc.setFont("helvetica", "bold");
    doc.text("RX / MEDICINES:", 20, 115);
    doc.setFont("helvetica", "normal");
    const medicineLines = doc.splitTextToSize(record.medicines || "N/A", 170);
    doc.text(medicineLines, 20, 122);
    if (record.note) {
      doc.setFont("helvetica", "italic");
      doc.text(`Note: ${record.note}`, 20, 200);
    }
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by Medical Portal", 105, 285, { align: "center" });
    doc.save(`Prescription_${record.type}.pdf`);
  };

  return (
    <div className="min-h-screen bg-slate-50/50 p-6 md:p-10 space-y-10 max-w-6xl mx-auto">
      {/* Header Section */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-6">
        <div className="space-y-2">
          <Button 
            variant="ghost" 
            onClick={() => router.back()} 
            className="group p-0 hover:bg-transparent text-slate-500 font-semibold"
          >
            <ArrowLeft className="mr-2 h-4 w-4 transition-transform group-hover:-translate-x-1" /> 
            Back to Patients
          </Button>
          <h2 className="text-4xl font-extrabold text-slate-900 tracking-tight">Clinical History</h2>
          <p className="text-slate-500 font-medium">Manage and view all medical records for Patient #{id.slice(-6)}</p>
        </div>

        <Dialog>
          <DialogTrigger asChild>
            <Button className="rounded-xl bg-blue-600 hover:bg-blue-700 px-8 py-6 shadow-xl shadow-blue-200 transition-all hover:scale-105 font-bold">
              <Plus className="mr-2 h-5 w-5" /> Add New Record
            </Button>
          </DialogTrigger>
          <DialogContent className="sm:max-w-[550px] rounded-3xl border-none shadow-2xl">
            <DialogHeader>
              <DialogTitle className="text-2xl font-bold text-slate-800">New Medical Entry</DialogTitle>
              <DialogDescription>Fill in the details to add a new record to the patient's history.</DialogDescription>
            </DialogHeader>
            <form onSubmit={handleAddRecord} className="space-y-5 pt-4">
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label className="text-slate-700 font-semibold">Record Type</Label>
                  <Input className="rounded-lg border-slate-200 focus:ring-blue-500" value={newRecord.type} onChange={(e) => setNewRecord({...newRecord, type: e.target.value})} placeholder="Prescription" required />
                </div>
                <div className="space-y-2">
                  <Label className="text-slate-700 font-semibold">Doctor Name</Label>
                  <Input className="rounded-lg border-slate-200" value={newRecord.doctor} onChange={(e) => setNewRecord({...newRecord, doctor: e.target.value})} required />
                </div>
              </div>
              <div className="space-y-2">
                <Label className="text-slate-700 font-semibold">Diagnosis</Label>
                <Input className="rounded-lg border-slate-200" value={newRecord.diagnosis} onChange={(e) => setNewRecord({...newRecord, diagnosis: e.target.value})} placeholder="Main issue/symptoms" required />
              </div>
              <div className="space-y-2">
                <Label className="text-slate-700 font-semibold">Medicines & Instructions</Label>
                <Textarea className="rounded-lg border-slate-200 min-h-[100px]" value={newRecord.medicines} onChange={(e) => setNewRecord({...newRecord, medicines: e.target.value})} placeholder="List medicines and dosages..." required />
              </div>
              <div className="space-y-2">
                <Label className="text-slate-700 font-semibold">Additional Note (Optional)</Label>
                <Textarea className="rounded-lg border-slate-200" value={newRecord.note} onChange={(e) => setNewRecord({...newRecord, note: e.target.value})} />
              </div>
              <Button type="submit" className="w-full bg-blue-600 hover:bg-blue-700 rounded-xl py-6 font-bold text-lg shadow-lg" disabled={isSubmitting}>
                {isSubmitting ? <Loader2 className="animate-spin" /> : "Save Medical Record"}
              </Button>
            </form>
          </DialogContent>
        </Dialog>
      </div>

      {/* Records List */}
      <div className="grid gap-4">
        {loading ? (
          <div className="flex flex-col items-center py-20 text-slate-400">
            <Loader2 className="h-10 w-10 animate-spin mb-4" />
            <p className="font-medium">Loading history...</p>
          </div>
        ) : records.length === 0 ? (
          <div className="text-center py-24 border-2 border-dashed border-slate-200 rounded-[40px] bg-white/50">
            <div className="bg-slate-100 h-16 w-16 rounded-full flex items-center justify-center mx-auto mb-4">
               <ClipboardList className="h-8 w-8 text-slate-400" />
            </div>
            <p className="text-slate-500 font-semibold text-xl">No clinical history found.</p>
            <p className="text-slate-400">Start by adding a new medical record above.</p>
          </div>
        ) : (
          records.map((rec) => (
            <Card key={rec._id || rec.id} className="group rounded-[28px] border-none shadow-sm bg-white hover:shadow-xl hover:shadow-blue-900/5 transition-all duration-300 overflow-hidden">
              <CardContent className="p-0">
                <div className="flex flex-col md:flex-row items-stretch">
                  {/* Left Icon/Type Section */}
                  <div className="bg-slate-50 p-6 flex items-center gap-5 md:w-2/3">
                    <div className="h-14 w-14 bg-white shadow-sm rounded-2xl flex items-center justify-center text-blue-600 shrink-0 group-hover:scale-110 transition-transform">
                      <FileText className="h-7 w-7" />
                    </div>
                    <div className="space-y-1">
                      <div className="flex flex-wrap items-center gap-3">
                        <h3 className="font-bold text-slate-800 text-xl">{rec.type}</h3>
                        <span className="bg-blue-100 text-blue-700 text-[10px] font-bold px-3 py-1 rounded-full flex items-center gap-1">
                          <Calendar className="h-3 w-3" />
                          {new Date(rec.createdAt || rec.date).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })}
                        </span>
                      </div>
                      <p className="text-sm text-slate-500 flex items-center gap-1.5 font-medium">
                        <User className="h-3.5 w-3.5" /> {rec.doctor}
                      </p>
                    </div>
                  </div>

                  {/* Right Actions Section */}
                  <div className="p-6 flex items-center gap-3 md:bg-slate-50/30 grow justify-end">
                    <Dialog>
                      <DialogTrigger asChild>
                        <Button 
                          variant="outline" 
                          className="rounded-xl border-slate-200 hover:bg-white font-bold h-12 px-6"
                          onClick={() => setSelectedRecord(rec)}
                        >
                          <Eye className="h-4 w-4 mr-2 text-blue-600" /> View
                        </Button>
                      </DialogTrigger>
                      <DialogContent className="rounded-3xl max-w-2xl">
                        <DialogHeader>
                          <DialogTitle className="text-2xl font-bold border-b pb-4">Record Details</DialogTitle>
                        </DialogHeader>
                        {selectedRecord && (
                          <div className="space-y-6 py-4">
                            <div className="grid grid-cols-2 gap-4 text-sm">
                              <div>
                                <p className="text-slate-400 font-medium">Doctor</p>
                                <p className="font-bold text-slate-800 text-lg">{selectedRecord.doctor}</p>
                              </div>
                              <div className="text-right">
                                <p className="text-slate-400 font-medium">Date</p>
                                <p className="font-bold text-slate-800 text-lg">{new Date(selectedRecord.createdAt).toLocaleDateString()}</p>
                              </div>
                            </div>
                            <div className="bg-blue-50 p-5 rounded-2xl">
                              <p className="text-blue-700 font-bold mb-1 text-sm uppercase tracking-wider">Diagnosis</p>
                              <p className="text-slate-800 font-medium">{selectedRecord.diagnosis}</p>
                            </div>
                            <div>
                              <p className="text-slate-400 font-bold mb-2 text-sm uppercase tracking-wider">Medicines</p>
                              <div className="bg-slate-50 p-5 rounded-2xl whitespace-pre-wrap border border-slate-100 italic">
                                {selectedRecord.medicines}
                              </div>
                            </div>
                            {selectedRecord.note && (
                              <div>
                                <p className="text-slate-400 font-bold mb-1 text-sm uppercase tracking-wider">Note</p>
                                <p className="text-slate-600">{selectedRecord.note}</p>
                              </div>
                            )}
                            <Button onClick={() => handleDownloadPDF(selectedRecord)} className="w-full bg-slate-900 h-12 rounded-xl">
                              <Download className="h-4 w-4 mr-2" /> Download PDF copy
                            </Button>
                          </div>
                        )}
                      </DialogContent>
                    </Dialog>

                    <Button 
                      onClick={() => handleDownloadPDF(rec)} 
                      className="rounded-xl bg-slate-900 hover:bg-black text-white font-bold h-12 px-6 shadow-lg shadow-slate-200"
                    >
                      <Download className="h-4 w-4 mr-2" /> PDF
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))
        )}
      </div>
    </div>
  );
}